Variability Framework: variability_framework_core.Thing Class Reference
variability_framework_core.Thing Class Reference
Public Member Functions
def __init__ (self, name, *type)
def relationship (self, relationship_class, *args)
Data Fields
name
type
Constructor & Destructor Documentation
__init__()
def variability_framework_core.Thing.__init__ (self, name, * type)
Reimplemented in variability_definition_2.Classifier, variability_definition_2.Comparison, variability_definition_2.Comparison_DATA_INTERFACE, variability_definition_2.Comparison_FLUID_INTERFACE, variability_definition_2.Comparison_MECHANICAL_INTERFACE, variability_definition_2.Comparison_Multiplicity, variability_definition_2.Comparison_PARENT, variability_definition_2.Comparison_POWER_INTERFACE, variability_definition_2.Comparison_THERMAL_INTERFACE, variability_definition_2.Comparison_Value, variability_definition_2.Design_Element, variability_definition_2.Difference, variability_definition_2.Difference_DATA_INTERFACE, variability_definition_2.Difference_FLUID_INTERFACE, variability_definition_2.Difference_MECHANICAL_INTERFACE, variability_definition_2.Difference_Multiplicity, variability_definition_2.Difference_PARENT, variability_definition_2.Difference_POWER_INTERFACE, variability_definition_2.Difference_Value, variability_definition_2.Mode, variability_definition_2.Parameter, variability_definition_2.Spacecraft, variability_definition_2.Subsystem, and variability_definition_2.Unit.
References variability_framework_core.Thing.__init__().
Referenced by variability_framework_core.Thing.__init__().
Member Function Documentation
relationship()
def variability_framework_core.Thing.relationship (self, relationship_class, * args)
References variability_framework_core.Thing.relationship().
Referenced by variability_framework_core.Thing.relationship().
Field Documentation
name
variability_framework_core.Thing.name
type
variability_framework_core.Thing.type
The documentation for this class was generated from the following file:
C:/Users/lt17550/University of Bristol/grp-Louis-Timperley-PhD - General/Variability_framework/variability-frame-work/variability_framework_core.py