Variability Framework: variability_definition_3.DIFFERENCE_LOCATION_IN_DESIGN Class Reference
variability_definition_3.DIFFERENCE_LOCATION_IN_DESIGN Class Reference
Public Member Functions
def __init__ (self, source, target)
def forbidden (self)
def invoke (self)
Public Member Functions inherited from variability_framework_core.Relationship
def __call__ (self)
Additional Inherited Members
Data Fields inherited from variability_framework_core.Relationship
name
a
b
inverse
Constructor & Destructor Documentation
__init__()
def variability_definition_3.DIFFERENCE_LOCATION_IN_DESIGN.__init__ (self, source, target)
Reimplemented from variability_framework_core.Relationship.
References variability_definition_3.DIFFERENCE_LOCATION_IN_DESIGN.__init__().
Referenced by variability_definition_3.DIFFERENCE_LOCATION_IN_DESIGN.__init__().
Member Function Documentation
forbidden()
def variability_definition_3.DIFFERENCE_LOCATION_IN_DESIGN.forbidden (self)
Reimplemented from variability_framework_core.Relationship.
References variability_definition_3.DIFFERENCE_LOCATION_IN_DESIGN.forbidden().
Referenced by variability_framework_core.Relationship.__call__(), and variability_definition_3.DIFFERENCE_LOCATION_IN_DESIGN.forbidden().
invoke()
def variability_definition_3.DIFFERENCE_LOCATION_IN_DESIGN.invoke (self)
Reimplemented from variability_framework_core.Relationship.
References variability_definition_3.DIFFERENCE_LOCATION_IN_DESIGN.invoke().
Referenced by variability_framework_core.Relationship.__call__(), and variability_definition_3.DIFFERENCE_LOCATION_IN_DESIGN.invoke().
The documentation for this class was generated from the following file:
C:/Users/lt17550/University of Bristol/grp-Louis-Timperley-PhD - General/Variability_framework/variability-frame-work/variability_definition_3.py