DRAGONS: test_result_viewer Namespace Reference
test_result_viewer Namespace Reference
Functions
def load_current_set (path_to_json='test_results/')
def process_section_results (json_files, path_to_json)
def flatten (xss)
def select_result_files (path_to_res, group, select_list)
def take_dataframe_average_robust (dataframe_list)
def display_k_fold_results (path_to_res)
def scaling_study ()
def return_number_of_elements_in_design (design_name, graph)
def return_set_of_requirement_labels (mission_name, graph)
def main ()
Function Documentation
display_k_fold_results()
def test_result_viewer.display_k_fold_results (path_to_res)
References display_k_fold_results(), flatten(), process_section_results(), select_result_files(), and take_dataframe_average_robust().
Referenced by display_k_fold_results(), main(), and scaling_study().
flatten()
def test_result_viewer.flatten (xss)
References flatten().
Referenced by display_k_fold_results(), flatten(), and scaling_study().
load_current_set()
def test_result_viewer.load_current_set (path_to_json = 'test_results/')
References load_current_set().
Referenced by load_current_set(), and scaling_study().
main()
def test_result_viewer.main ()
References display_k_fold_results(), and main().
Referenced by main().
process_section_results()
def test_result_viewer.process_section_results (json_files, path_to_json)
References process_section_results().
Referenced by display_k_fold_results(), process_section_results(), and scaling_study().
return_number_of_elements_in_design()
def test_result_viewer.return_number_of_elements_in_design (design_name, graph)
References return_number_of_elements_in_design().
Referenced by return_number_of_elements_in_design(), and scaling_study().
return_set_of_requirement_labels()
def test_result_viewer.return_set_of_requirement_labels (mission_name, graph)
References return_set_of_requirement_labels().
Referenced by return_set_of_requirement_labels(), and scaling_study().
scaling_study()
def test_result_viewer.scaling_study ()
References display_k_fold_results(), flatten(), load_current_set(), load_designs.Load_designs(), process_section_results(), return_number_of_elements_in_design(), return_set_of_requirement_labels(), and scaling_study().
Referenced by scaling_study().
select_result_files()
def test_result_viewer.select_result_files (path_to_res, group, select_list)
References select_result_files().
Referenced by display_k_fold_results(), and select_result_files().
take_dataframe_average_robust()
def test_result_viewer.take_dataframe_average_robust (dataframe_list)
References take_dataframe_average_robust().
Referenced by display_k_fold_results(), and take_dataframe_average_robust().