DRAGONS: design_comparison.design_comparison Namespace Reference
design_comparison.design_comparison Namespace Reference
Data Structures
class comparison_record
class difference_record
class object_location_pair
Functions
def identify_pairwise_design_union (names, graphs)
def identify_dissimilar_node_classifiers (names, graphs)
def identify_value_differences (names, graphs)
def identify_child_classifier (value1, des1_element, name, graph)
def identify_target_classifier (des_element, target_uid, relationship_type, name, graph)
def identify_element_children (des_element, name, graph)
def numerical_value_comparison (comparisons, key, des_elements, des_names)
def value_set_comparison (comparisons, value, key, des_elements, des_names)
def single_value_comparison (comparisons, value, key, des_elements, des_names)
def property_comparison (comparisons, key)
def relationship_comparison (comparisons, des_elements, graph)
def compare_nodes (comparisons, des_elements, names, graph)
def traverse_tree (brief_name, comparisons, des_elements, names, graphs)
def diff_algorithm (brief_name, names, repeated_differences, graphs)
def generate_comparison_stats (brief_name, graph)
def population_wide_diff_algorithm (missions_list, graph)
def population_wide_generate_comparison_stats (missions_list, graph)
Function Documentation
compare_nodes()
def design_comparison.design_comparison.compare_nodes (comparisons, des_elements, names, graph)
Compare properties and relationships between nodes in different designs.
This function compares properties and relationships between nodes in different designs.
It collects differences between the nodes and records them as "difference" nodes in the comparisons list.
@param comparisons: The list of comparison records to which differences will be appended.
@type comparisons: list of comparison_record
@param des_elements: A list of object_location_pair objects representing design elements to compare.
@type des_elements: list of object_location_pair
@param names: A list of design names corresponding to des_elements.
@type names: list of str
@param graph: The Neo4j graph database connection.
@type graph: neo4j.Graph
@return: The updated list of comparison records with differences appended.
@rtype: list of comparison_record
@pre 'comparisons' should be a list of comparison_record objects, 'des_elements' should be a list of object_location_pair objects,
'names' should be a list of corresponding design names, and 'graph' should be a valid Neo4j graph database connection.
@see: This function is used to compare properties and relationships between nodes in different designs.
References design_comparison.design_comparison.compare_nodes(), design_comparison.design_comparison.property_comparison(), and design_comparison.design_comparison.relationship_comparison().
Referenced by design_comparison.design_comparison.compare_nodes(), and design_comparison.design_comparison.traverse_tree().
diff_algorithm()
def design_comparison.design_comparison.diff_algorithm (brief_name, names, repeated_differences, graphs)
Perform a differential comparison of designs represented in Neo4j graphs.
This function performs a differential comparison of designs represented in Neo4j graphs.
It compares nodes at each level of the design hierarchy, identifying differences and storing them as 'Comparison'
and 'Difference' nodes in the database.
@param brief_name: A brief name or identifier for the comparison group.
@type brief_name: str
@param names: A list of design names corresponding to Neo4j graphs.
@type names: list of str
@param graphs: A list of Neo4j graph database connections corresponding to each design.
@type graphs: list of neo4j.Graph
@return: None
@pre 'brief_name' should be a valid identifier, 'names' should be a list of design names,
and 'graphs' should be a list of valid Neo4j graph database connections.
@see: This function performs a differential comparison of designs represented in Neo4j graphs
and stores the results in the database.
References design_comparison.design_comparison.diff_algorithm(), and design_comparison.design_comparison.traverse_tree().
Referenced by design_comparison.design_comparison.diff_algorithm(), and design_comparison.design_comparison.population_wide_diff_algorithm().
generate_comparison_stats()
def design_comparison.design_comparison.generate_comparison_stats (brief_name, graph)
Generate statistics and plots for a comparison group in the Neo4j database.
This function generates statistics and various plots for a specified comparison group
stored in the Neo4j database. It retrieves the counts of 'Difference' and 'Comparison' nodes
for the given comparison group, as well as additional data for plotting.
@param brief_name: A brief name or identifier for the comparison group.
@type brief_name: str
@param graph: A Neo4j graph database connection.
@type graph: neo4j.Graph
@return: None
@pre 'brief_name' should be a valid identifier, and 'graph' should be a valid Neo4j graph database connection.
@see: This function generates statistics and plots for a specified comparison group in the Neo4j database.
References design_comparison.design_comparison.generate_comparison_stats().
Referenced by design_comparison.design_comparison.generate_comparison_stats(), and design_comparison.design_comparison.population_wide_generate_comparison_stats().
identify_child_classifier()
def design_comparison.design_comparison.identify_child_classifier (value1, des1_element, name, graph)
Identify the classifier of a child element in a specific design.
This function takes the unique identifier 'value1' of a child element, the parent element 'des1_element', and the design name 'name'.
It matches the child element in the specified design and returns its classifier.
@param value1: The unique identifier of the child element.
@type value1: str
@param des1_element: The parent element in the design hierarchy.
@type des1_element: list of neo4j.Node
@param name: The name of the design in which to search for the child element.
@type name: str
@param graph: The Neo4j graph database connection for the specified design.
@type graph: neo4j.Graph
@return: The classifier of the identified child element.
@rtype: list of dict
@pre 'value1' should be a valid unique identifier, 'des1_element' should be a list of Neo4j nodes representing the parent element,
     'name' should be a valid design name, and 'graph' should be a Neo4j graph database connection.
@see: This function is used to identify the classifier of a child element in a specific design.
References design_comparison.design_comparison.identify_child_classifier().
Referenced by design_comparison.design_comparison.identify_child_classifier(), and design_comparison.design_comparison.traverse_tree().
identify_dissimilar_node_classifiers()
def design_comparison.design_comparison.identify_dissimilar_node_classifiers (names, graphs)
Identify and return dissimilar node classifiers between two designs.
This function takes two design names and their corresponding Neo4j graph database connections.
It identifies node classifiers that are dissimilar between the two designs and returns them.
@param names: A list containing the names of the two designs to be compared.
@type names: list of str
@param graphs: A list containing Neo4j graph database connections for the two designs.
@type graphs: list of neo4j.Graph
@return: A result set containing dissimilar node classifiers between the two designs.
@rtype: neo4j.Result
@pre 'names' should be a list containing exactly two design names as strings, and 'graphs' should be a list containing
     the corresponding Neo4j graph database connections.
@see: This function is used to identify and return dissimilar node classifiers between two designs in Neo4j.
References design_comparison.design_comparison.identify_dissimilar_node_classifiers().
Referenced by design_comparison.design_comparison.identify_dissimilar_node_classifiers().
identify_element_children()
def design_comparison.design_comparison.identify_element_children (des_element, name, graph)
Identify the children of a specified design element.
This function takes a design element 'des_element', the design name 'name', and the Neo4j graph database connection 'graph'.
It matches the children of the specified design element and returns their unique identifiers.
@param des_element: The design element for which to identify children.
@type des_element: list of neo4j.Node
@param name: The name of the design in which to search for children.
@type name: str
@param graph: The Neo4j graph database connection for the specified design.
@type graph: neo4j.Graph
@return: A list of unique identifiers for the identified children.
@rtype: list of dict
@pre 'des_element' should be a list of Neo4j nodes representing the design element, 'name' should be a valid design name,
     and 'graph' should be a Neo4j graph database connection.
@see: This function is used to identify the children of a specified design element in Neo4j.
References design_comparison.design_comparison.identify_element_children().
Referenced by design_comparison.design_comparison.identify_element_children(), and design_comparison.design_comparison.traverse_tree().
identify_pairwise_design_union()
def design_comparison.design_comparison.identify_pairwise_design_union (names, graphs)
Identify and mark elements that are shared classifiers between two designs.
This function takes two design names and their corresponding Neo4j graph database connections.
It identifies elements that are shared classifiers between the two designs and marks them by adding a
common comparison name as a label to these elements. The comparison name is generated based on the input design names.
@param names: A list containing the names of the two designs to be compared.
@type names: list of str
@param graphs: A list containing Neo4j graph database connections for the two designs.
@type graphs: list of neo4j.Graph
@pre 'names' should be a list containing exactly two design names as strings, and 'graphs' should be a list containing
     the corresponding Neo4j graph database connections.
@see: This function is used to identify and mark shared classifiers between two designs in Neo4j.
References design_comparison.design_comparison.identify_pairwise_design_union().
Referenced by design_comparison.design_comparison.identify_pairwise_design_union().
identify_target_classifier()
def design_comparison.design_comparison.identify_target_classifier (des_element, target_uid, relationship_type, name, graph)
Identify the classifier of a target element related to a specified design element.
This function takes a design element 'des_element' (parent), a target element unique identifier 'target_uid', a relationship type 'relationship_type',
the design name 'name', and the Neo4j graph database connection 'graph'. It matches the target element related to the specified design element
using the given relationship type and returns its classifier.
@param des_element: The design element (parent) in the relationship.
@type des_element: list of neo4j.Node
@param target_uid: The unique identifier of the target element.
@type target_uid: str
@param relationship_type: The type of relationship connecting the design element and the target element.
@type relationship_type: str
@param name: The name of the design in which to search for the target element.
@type name: str
@param graph: The Neo4j graph database connection for the specified design.
@type graph: neo4j.Graph
@return: The classifier of the identified target element.
@rtype: list of dict
@pre 'des_element' should be a list of Neo4j nodes representing the design element (parent), 'target_uid' should be a valid unique identifier,
     'relationship_type' should be a valid relationship type, 'name' should be a valid design name, and 'graph' should be a Neo4j graph database connection.
@see: This function is used to identify the classifier of a target element related to a specified design element in Neo4j.
References design_comparison.design_comparison.identify_target_classifier().
Referenced by design_comparison.design_comparison.identify_target_classifier(), and design_comparison.design_comparison.relationship_comparison().
identify_value_differences()
def design_comparison.design_comparison.identify_value_differences (names, graphs)
Identify and mark parameter value differences between two designs.
This function takes two design names and their corresponding Neo4j graph database connections.
It identifies parameter value differences between the two designs and marks the parameters by adding a
common comparison name as a label to these parameters. The comparison name is generated based on the input design names.
@param names: A list containing the names of the two designs to be compared.
@type names: list of str
@param graphs: A list containing Neo4j graph database connections for the two designs.
@type graphs: list of neo4j.Graph
@pre 'names' should be a list containing exactly two design names as strings, and 'graphs' should be a list containing
     the corresponding Neo4j graph database connections.
@see: This function is used to identify and mark parameter value differences between two designs in Neo4j.
References design_comparison.design_comparison.identify_value_differences().
Referenced by design_comparison.design_comparison.identify_value_differences().
numerical_value_comparison()
def design_comparison.design_comparison.numerical_value_comparison (comparisons, key, des_elements, des_names)
Compare numerical property values of design elements.
This function compares numerical property values of design elements across different designs.
It takes a list of comparison records 'comparisons', a 'key' object specifying the property to compare,
a list of design elements 'des_elements', and a list of design names 'des_names'.
@param comparisons: The list of comparison records to which differences will be appended.
@type comparisons: list of comparison_record
@param key: The key object specifying the property to compare.
@type key: object_location_pair
@param des_elements: A list of design elements from different designs to compare.
@type des_elements: list of list of neo4j.Node
@param des_names: A list of design names corresponding to the design elements.
@type des_names: list of str
@return: The updated list of comparison records with differences appended.
@rtype: list of comparison_record
@pre 'comparisons' should be a list of comparison_record objects, 'key' should specify a valid property to compare,
     'des_elements' should be a list of lists of Neo4j nodes representing design elements, and 'des_names' should be a list
     of valid design names corresponding to the design elements.
@see: This function is used to compare numerical property values of design elements across different designs.
References design_comparison.design_comparison.numerical_value_comparison().
Referenced by design_comparison.design_comparison.numerical_value_comparison(), and design_comparison.design_comparison.property_comparison().
population_wide_diff_algorithm()
def design_comparison.design_comparison.population_wide_diff_algorithm (missions_list, graph)
Perform a population-wide difference analysis for a list of missions.
This function iterates through a list of missions and their associated designs
and performs a difference analysis for each mission using the 'diff_algorithm' function.
It aims to analyze differences across the entire population of missions.
@param missions_list: A dictionary containing mission names as keys and lists of designs as values.
@type missions_list: dict
@param graph: A Neo4j graph database connection.
@type graph: neo4j.Graph
@return: None
@pre 'missions_list' should be a valid dictionary with mission names and associated design lists,
     and 'graph' should be a valid Neo4j graph database connection.
@see: The 'diff_algorithm' function is used to perform difference analysis for individual missions.
References design_comparison.design_comparison.diff_algorithm(), and design_comparison.design_comparison.population_wide_diff_algorithm().
Referenced by design_comparison.design_comparison.population_wide_diff_algorithm().
population_wide_generate_comparison_stats()
def design_comparison.design_comparison.population_wide_generate_comparison_stats (missions_list, graph)
Generate comparison statistics for a population of missions.
This function iterates through a list of missions and generates comparison statistics for each mission
using the 'generate_comparison_stats' function. It aims to generate statistics for the entire population
of missions.
@param missions_list: A dictionary containing mission names as keys and lists of designs as values.
@type missions_list: dict
@param graph: A Neo4j graph database connection.
@type graph: neo4j.Graph
@return: None
@pre 'missions_list' should be a valid dictionary with mission names and associated design lists,
     and 'graph' should be a valid Neo4j graph database connection.
@see: The 'generate_comparison_stats' function is used to generate comparison statistics for individual missions.
References design_comparison.design_comparison.generate_comparison_stats(), and design_comparison.design_comparison.population_wide_generate_comparison_stats().
Referenced by design_comparison.design_comparison.population_wide_generate_comparison_stats().
property_comparison()
def design_comparison.design_comparison.property_comparison (comparisons, key)
Compare a property across different design elements and designs.
This function compares a property across different design elements and designs.
It constructs a comparison object and then iterates over each design element, changing the base design being compared to.
@param comparisons: The list of comparison records to which differences will be appended.
@type comparisons: list of comparison_record
@param key: The key object specifying the property to compare.
@type key: object_location_pair
@return: The updated list of comparison records with differences appended.
@rtype: list of comparison_record
@pre 'comparisons' should be a list of comparison_record objects, and 'key' should specify a valid property to compare.
@see: This function is used to compare a property across different design elements and designs.
References design_comparison.design_comparison.numerical_value_comparison(), design_comparison.design_comparison.property_comparison(), design_comparison.design_comparison.single_value_comparison(), and design_comparison.design_comparison.value_set_comparison().
Referenced by design_comparison.design_comparison.compare_nodes(), and design_comparison.design_comparison.property_comparison().
relationship_comparison()
def design_comparison.design_comparison.relationship_comparison (comparisons, des_elements, graph)
Compare relationships between different design elements and designs.
This function compares relationships between different design elements and designs.
It finds each element's relationship types, switches the base design for comparison,
and then compares the relationships and classifiers between designs.
@param comparisons: The list of comparison records to which differences will be appended.
@type comparisons: list of comparison_record
@param des_elements: A list of object_location_pair objects representing design elements to compare.
@type des_elements: list of object_location_pair
@param graph: The Neo4j graph database connection.
@type graph: neo4j.Graph
@return: The updated list of comparison records with differences appended.
@rtype: list of comparison_record
@pre 'comparisons' should be a list of comparison_record objects, 'des_elements' should be a list of object_location_pair objects,
and 'graph' should be a valid Neo4j graph database connection.
@see: This function is used to compare relationships between different design elements and designs.
References design_comparison.design_comparison.identify_target_classifier(), and design_comparison.design_comparison.relationship_comparison().
Referenced by design_comparison.design_comparison.compare_nodes(), and design_comparison.design_comparison.relationship_comparison().
single_value_comparison()
def design_comparison.design_comparison.single_value_comparison (comparisons, value, key, des_elements, des_names)
Compare a single value for a specific property of design elements.
This function compares a single value for a specific property of design elements across different designs.
It takes a list of comparison records 'comparisons', a 'value' to compare, a 'key' object specifying the property to compare,
a list of design elements 'des_elements', and a list of design names 'des_names'.
@param comparisons: The list of comparison records to which differences will be appended.
@type comparisons: list of comparison_record
@param value: The value to compare within the property.
@type value: str
@param key: The key object specifying the property to compare.
@type key: object_location_pair
@param des_elements: A list of design elements from different designs to compare.
@type des_elements: list of list of neo4j.Node
@param des_names: A list of design names corresponding to the design elements.
@type des_names: list of str
@return: The updated list of comparison records with differences appended.
@rtype: list of comparison_record
@pre 'comparisons' should be a list of comparison_record objects, 'value' should be a valid value to compare,
     'key' should specify a valid property to compare, 'des_elements' should be a list of lists of Neo4j nodes representing
     design elements, and 'des_names' should be a list of valid design names corresponding to the design elements.
@see: This function is used to compare a single value for a specific property of design elements across different designs.
References design_comparison.design_comparison.single_value_comparison().
Referenced by design_comparison.design_comparison.property_comparison(), and design_comparison.design_comparison.single_value_comparison().
traverse_tree()
def design_comparison.design_comparison.traverse_tree (brief_name, comparisons, des_elements, names, graphs)
Recursively traverse a tree structure of nodes to compare them.
This function recursively traverses a tree structure of nodes to compare them.
It compares nodes at each level, starting with the root nodes, and continues down to the leaf nodes.
@param brief_name: A brief name or identifier for the comparison group.
@type brief_name: str
@param comparisons: The list of comparison records to which differences will be appended.
@type comparisons: list of comparison_record
@param des_elements: A list of object_location_pair objects representing design elements to compare at the current level.
@type des_elements: list of object_location_pair
@param names: A list of design names corresponding to des_elements.
@type names: list of str
@param graphs: A list of Neo4j graph database connections corresponding to each design.
@type graphs: list of neo4j.Graph
@return: The updated list of comparison records with differences appended.
@rtype: list of comparison_record
@pre 'brief_name' should be a valid identifier, 'comparisons' should be a list of comparison_record objects,
'des_elements' should be a list of object_location_pair objects, 'names' should be a list of corresponding design names,
and 'graphs' should be a list of valid Neo4j graph database connections.
@see: This function is used to recursively traverse a tree structure of nodes and compare them at each level.
References design_comparison.design_comparison.compare_nodes(), design_comparison.design_comparison.identify_child_classifier(), design_comparison.design_comparison.identify_element_children(), and design_comparison.design_comparison.traverse_tree().
Referenced by design_comparison.design_comparison.diff_algorithm(), and design_comparison.design_comparison.traverse_tree().
value_set_comparison()
def design_comparison.design_comparison.value_set_comparison (comparisons, value, key, des_elements, des_names)
Compare sets of values for a specific property of design elements.
This function compares sets of values for a specific property of design elements across different designs.
It takes a list of comparison records 'comparisons', a 'value' to compare, a 'key' object specifying the property to compare,
a list of design elements 'des_elements', and a list of design names 'des_names'.
@param comparisons: The list of comparison records to which differences will be appended.
@type comparisons: list of comparison_record
@param value: The value to compare within the property set.
@type value: str
@param key: The key object specifying the property to compare.
@type key: object_location_pair
@param des_elements: A list of design elements from different designs to compare.
@type des_elements: list of list of neo4j.Node
@param des_names: A list of design names corresponding to the design elements.
@type des_names: list of str
@return: The updated list of comparison records with differences appended.
@rtype: list of comparison_record
@pre 'comparisons' should be a list of comparison_record objects, 'value' should be a valid value to compare,
     'key' should specify a valid property to compare, 'des_elements' should be a list of lists of Neo4j nodes representing
     design elements, and 'des_names' should be a list of valid design names corresponding to the design elements.
@see: This function is used to compare sets of values for a specific property of design elements across different designs.
References design_comparison.design_comparison.value_set_comparison().
Referenced by design_comparison.design_comparison.property_comparison(), and design_comparison.design_comparison.value_set_comparison().