Variability Framework: mapping_definition_1 Namespace Reference
mapping_definition_1 Namespace Reference
Functions
def lists_overlap (a, b)
def identify_target_type (target_lables)
def define_labelled_types ()
def define_mapped_types ()
Variables
list explored_types
list mapped_types
Function Documentation
define_labelled_types()
def mapping_definition_1.define_labelled_types ()
References define_labelled_types().
Referenced by define_labelled_types().
define_mapped_types()
def mapping_definition_1.define_mapped_types ()
References define_mapped_types().
Referenced by define_mapped_types().
identify_target_type()
def mapping_definition_1.identify_target_type (target_lables)
References identify_target_type(), and lists_overlap().
Referenced by identify_target_type().
lists_overlap()
def mapping_definition_1.lists_overlap (a, b)
References lists_overlap().
Referenced by identify_target_type(), and lists_overlap().
Variable Documentation
explored_types
list mapping_definition_1.explored_types
Initial value:
=  ['Comparison',
                     'Difference',
                     'Difference_Value',
                     'Difference_PARENT',
                     'Difference_DATA_INTERFACE',
                     'Difference_FLUID_INTERFACE',
                     'Difference_MECHANICAL_INTERFACE',
                     'Difference_Multiplicity',
                     'Difference_POWER_INTERFACE',
                     'Comparison_DATA_INTERFACE',
                     'Comparison_FLUID_INTERFACE',
                     'Comparison_MECHANICAL_INTERFACE',
                     'Comparison_Multiplicity',
                     'Comparison_PARENT',
                     'Comparison_POWER_INTERFACE',
                     'Comparison_THERMAL_INTERFACE',
                     'Comparison_Value',
                     'Design_Element',
                     'Parameter',
                     'Component',
                     'Mode',
                     'Condition',
                     'Spacecraft',
                     'Subsystem',
                     'Unit']
mapped_types
list mapping_definition_1.mapped_types
Initial value:
=  ['Comparison',
                'Difference',
                'Classifier',
                'Design_Element',
                'Parameter',
                'Component',
                'Mode',
                'Condition',
                'Spacecraft',
                'Subsystem',
                'Unit']