Variability Framework: interface Namespace Reference
interface Namespace Reference
Functions
def initialise ()
def display_processing_progress (root, task_name, progress)
def display_diagram_commands (root, missions_list)
Function Documentation
display_diagram_commands()
def interface.display_diagram_commands (root, missions_list)
Display a GUI for generating diagram commands.
Args:
    root (tk.Tk): The root window of the GUI application.
    missions_list (dict): A dictionary containing missions and their associated designs.
Returns:
    None
References display_diagram_commands().
Referenced by display_diagram_commands(), and main.main().
display_processing_progress()
def interface.display_processing_progress (root, task_name, progress)
References display_processing_progress().
Referenced by display_processing_progress().
initialise()
def interface.initialise ()
Initialize the GUI application.
Creates and configures the main GUI window with a specified title,
maximum size, and background color.
Returns:
    tk.Tk: The root window of the GUI application.
References initialise().
Referenced by initialise(), and main.main().