Variability Framework: main Namespace Reference
main Namespace Reference
Functions
def main ()
Variables
graph = Graph("bolt://127.0.0.1:7687", auth=('neo4j', 'test'))
Graph database config.
Function Documentation
main()
def main.main ()
References database_tools.clear_database(), interface.display_diagram_commands(), interface.initialise(), main(), design_comparison.population_wide_diff_algorithm(), data_extraction.process_component_classifier_data(), data_extraction.process_condition_classifier_data(), data_extraction.process_design_data(), data_extraction.process_mode_classifier_data(), data_extraction.process_parameter_classifier_data(), and data_extraction.read_data().
Referenced by main().
Variable Documentation
graph
main.graph = Graph("bolt://127.0.0.1:7687", auth=('neo4j', 'test'))
Graph database config.