DRAGONS: design_playground Namespace Reference
design_playground Namespace Reference
Functions
def run_process_identification_tool (process_elements)
def identify_process_elements (design_query)
def main ()
Function Documentation
identify_process_elements()
def design_playground.identify_process_elements (design_query)
References identify_process_elements().
Referenced by identify_process_elements().
main()
def design_playground.main ()
References main().
Referenced by main().
run_process_identification_tool()
def design_playground.run_process_identification_tool (process_elements)
References run_process_identification_tool().
Referenced by run_process_identification_tool().