DRAGONS: load_designs Namespace Reference
load_designs Namespace Reference
Functions
def Load_designs (missions, do_comparison=True)
def main ()
Variables
graph = Graph("bolt://127.0.0.1:7687", auth=('neo4j', 'test'))
Graph database config.
Function Documentation
Load_designs()
def load_designs.Load_designs (missions, do_comparison = True)
References Load_designs().
Referenced by Load_designs(), main(), and test_result_viewer.scaling_study().
main()
def load_designs.main ()
References Load_designs(), and main().
Referenced by main().
Variable Documentation
graph
load_designs.graph = Graph("bolt://127.0.0.1:7687", auth=('neo4j', 'test'))
Graph database config.