Variability Framework: data_extraction Namespace Reference
data_extraction Namespace Reference
Functions
def read_data (name)
def generate_uid (data, type_tag)
def process_component_classifier_data (data, graph)
def process_condition_classifier_data (data, graph)
def process_mode_classifier_data (data, graph)
def process_parameter_classifier_data (data, graph)
def process_design_data (design_name, data, ontology_graph)
Function Documentation
generate_uid()
def data_extraction.generate_uid (data, type_tag)
Generate unique identifiers (UIDs) and add them as a new column in a DataFrame.
This function takes a pandas DataFrame 'data' and a 'type_tag' as input. It generates
unique identifiers by combining the 'type_tag' and the 'name' column values for each row
in the DataFrame. The UIDs are added as a new 'uid' column in the DataFrame.
@param data: The input DataFrame containing at least a 'name' column.
@type data: pandas.DataFrame
@param type_tag: A string used as a prefix to create unique identifiers.
@type type_tag: str
@return: The input DataFrame with an additional 'uid' column containing the generated UIDs.
@rtype: pandas.DataFrame
@pre The 'data' DataFrame must contain a 'name' column.
@post The returned DataFrame will have an additional 'uid' column with unique identifiers.
@warning If the 'name' column does not exist in the input DataFrame, this function will raise
         a KeyError.
@see: You can use the pandas library for further DataFrame manipulation and analysis.
References generate_uid().
Referenced by generate_uid(), variability_framework_core.load_classifier_rules(), process_component_classifier_data(), process_condition_classifier_data(), process_design_data(), process_mode_classifier_data(), and process_parameter_classifier_data().
process_component_classifier_data()
def data_extraction.process_component_classifier_data (data, graph)
Process and insert component classifier data into a Neo4j graph database.
This function takes component classifier data in the form of a pandas DataFrame 'data'
and inserts it into a Neo4j graph database specified by the 'graph' parameter. The function
performs several data processing steps, including generating unique identifiers, filtering,
and formatting the data, and creating nodes and relationships in the graph.
@param data: The input DataFrame containing component classifier data.
@type data: pandas.DataFrame
@param graph: The Neo4j graph database connection.
@type graph: neo4j.Graph
@pre The 'data' DataFrame must conform to a specific structure with defined columns.
@post The component classifier data is inserted into the Neo4j graph database.
@warning This function assumes a specific data structure and may not work with arbitrary dataframes.
@see: You can use the neo4j package for interacting with Neo4j databases and pandas for data manipulation.
References generate_uid(), process_component_classifier_data(), database_tools.process_relationships(), and database_tools.run_neo_query().
Referenced by main.main(), and process_component_classifier_data().
process_condition_classifier_data()
def data_extraction.process_condition_classifier_data (data, graph)
Process and insert condition classifier data into a Neo4j graph database.
This function takes condition classifier data in the form of a pandas DataFrame 'data'
and inserts it into a Neo4j graph database specified by the 'graph' parameter. The function
performs several data processing steps, including generating unique identifiers, filtering,
and formatting the data, and creating nodes in the graph.
@param data: The input DataFrame containing condition classifier data.
@type data: pandas.DataFrame
@param graph: The Neo4j graph database connection.
@type graph: neo4j.Graph
@pre The 'data' DataFrame must conform to a specific structure with defined columns.
@post The condition classifier data is inserted into the Neo4j graph database.
@warning This function assumes a specific data structure and may not work with arbitrary dataframes.
@see: You can use the neo4j package for interacting with Neo4j databases and pandas for data manipulation.
References generate_uid(), process_condition_classifier_data(), and database_tools.run_neo_query().
Referenced by main.main(), and process_condition_classifier_data().
process_design_data()
def data_extraction.process_design_data (design_name, data, ontology_graph)
Process and insert design data into a Neo4j graph database.
This function takes design data, represented as a pandas DataFrame 'data', and inserts it into a Neo4j
graph database specified by the 'ontology_graph' parameter. The function performs several data processing
steps, including generating unique identifiers, filtering, and formatting the data, and creating nodes and
relationships in the graph to represent design elements and their properties.
@param design_name: The name or identifier for the specific design instance being processed.
@type design_name: str
@param data: The input DataFrame containing design data.
@type data: pandas.DataFrame
@param ontology_graph: The Neo4j graph database connection for ontology data.
@type ontology_graph: neo4j.Graph
@pre The 'data' DataFrame must conform to a specific structure with defined columns.
@post The design data is inserted into the Neo4j graph database with relationships to classifiers, children, and interfaces.
@warning This function assumes a specific data structure and may not work with arbitrary dataframes.
@see: You can use the neo4j package for interacting with Neo4j databases and pandas for data manipulation.
References generate_uid(), process_design_data(), database_tools.process_relationships(), ontology_checking.process_valid_relationships(), database_tools.run_neo_query(), and ontology_checking.run_valid_neo_query().
Referenced by main.main(), and process_design_data().
process_mode_classifier_data()
def data_extraction.process_mode_classifier_data (data, graph)
Process and insert mode classifier data into a Neo4j graph database.
This function takes mode classifier data in the form of a pandas DataFrame 'data'
and inserts it into a Neo4j graph database specified by the 'graph' parameter. The function
performs several data processing steps, including generating unique identifiers, filtering,
and formatting the data, and creating nodes and relationships in the graph.
@param data: The input DataFrame containing mode classifier data.
@type data: pandas.DataFrame
@param graph: The Neo4j graph database connection.
@type graph: neo4j.Graph
@pre The 'data' DataFrame must conform to a specific structure with defined columns.
@post The mode classifier data is inserted into the Neo4j graph database with relationships to allowed owners and conditions.
@warning This function assumes a specific data structure and may not work with arbitrary dataframes.
@see: You can use the neo4j package for interacting with Neo4j databases and pandas for data manipulation.
References generate_uid(), process_mode_classifier_data(), database_tools.process_relationships(), and database_tools.run_neo_query().
Referenced by main.main(), and process_mode_classifier_data().
process_parameter_classifier_data()
def data_extraction.process_parameter_classifier_data (data, graph)
Process and insert parameter classifier data into a Neo4j graph database.
This function takes parameter classifier data in the form of a pandas DataFrame 'data'
and inserts it into a Neo4j graph database specified by the 'graph' parameter. The function
performs several data processing steps, including generating unique identifiers, filtering,
and formatting the data, and creating nodes and relationships in the graph.
@param data: The input DataFrame containing parameter classifier data.
@type data: pandas.DataFrame
@param graph: The Neo4j graph database connection.
@type graph: neo4j.Graph
@pre The 'data' DataFrame must conform to a specific structure with defined columns.
@post The parameter classifier data is inserted into the Neo4j graph database with relationships to owners (Components, Subsystems, and Units).
@warning This function assumes a specific data structure and may not work with arbitrary dataframes.
@see: You can use the neo4j package for interacting with Neo4j databases and pandas for data manipulation.
References generate_uid(), process_parameter_classifier_data(), database_tools.process_relationships(), database_tools.process_relationships_to_generic(), and database_tools.run_neo_query().
Referenced by main.main(), and process_parameter_classifier_data().
read_data()
def data_extraction.read_data (name)
Read data from a CSV file and return it as a DataFrame.
This function reads a CSV file located in the './data/' directory with the
given 'name' and returns its contents as a pandas DataFrame.
@param name: The name of the CSV file (excluding the '.csv' extension).
@type name: str
@return: A pandas DataFrame containing the data from the CSV file.
@rtype: pandas.DataFrame
@pre The CSV file must exist in the './data/' directory.
@post The returned DataFrame will contain the data from the CSV file.
@warning If the specified CSV file does not exist, this function will raise
         a FileNotFoundError.
@see: You can use the pandas library for further data manipulation and analysis.
References read_data().
Referenced by variability_definition_1.define_framework(), main.main(), and read_data().