DRAGONS: variability_framework_tools.variability_framework_textual_core Namespace Reference
variability_framework_tools.variability_framework_textual_core Namespace Reference
Data Structures
class Relationship
class Rules
class Thing
Functions
def load_classifier_rules (data, rules, classifier_type)
def identify_relationship_class_from_name (relationship_tag, framework_module)
def identify_relationship_class (relationship_tag, framework_module)
Function Documentation
identify_relationship_class()
def variability_framework_tools.variability_framework_textual_core.identify_relationship_class (relationship_tag, framework_module)
References variability_framework_tools.variability_framework_textual_core.identify_relationship_class().
Referenced by variability_framework_tools.variability_framework_textual_core.Rules.add_relevant_inverse(), and variability_framework_tools.variability_framework_textual_core.identify_relationship_class().
identify_relationship_class_from_name()
def variability_framework_tools.variability_framework_textual_core.identify_relationship_class_from_name (relationship_tag, framework_module)
References variability_framework_tools.variability_framework_textual_core.identify_relationship_class_from_name().
Referenced by variability_framework_tools.variability_framework_textual_core.Rules.add_relevant_inverse(), and variability_framework_tools.variability_framework_textual_core.identify_relationship_class_from_name().
load_classifier_rules()
def variability_framework_tools.variability_framework_textual_core.load_classifier_rules (data, rules, classifier_type)
References variability_framework_tools.variability_framework_textual_core.load_classifier_rules().
Referenced by variability_framework_tools.variability_framework_textual_core.load_classifier_rules().