Variability Framework: mapping_definition_2 Namespace Reference
mapping_definition_2 Namespace Reference
Functions
def lists_overlap (a, b)
def identify_target_type (target_lables)
def define_labelled_types ()
Variables
list explored_types
list mapped_types = ['Comparison']
Function Documentation
define_labelled_types()
def mapping_definition_2.define_labelled_types ()
References define_labelled_types().
Referenced by define_labelled_types().
identify_target_type()
def mapping_definition_2.identify_target_type (target_lables)
References identify_target_type().
Referenced by identify_target_type().
lists_overlap()
def mapping_definition_2.lists_overlap (a, b)
References lists_overlap().
Referenced by lists_overlap().
Variable Documentation
explored_types
list mapping_definition_2.explored_types
Initial value:
=  ['Comparison',
                     'Difference',
                     'Difference_Value',
                     'Difference_PARENT',
                     'Difference_DATA_INTERFACE',
                     'Difference_FLUID_INTERFACE',
                     'Difference_MECHANICAL_INTERFACE',
                     'Difference_Multiplicity',
                     'Difference_POWER_INTERFACE',
                     'Design_Element']
mapped_types
list mapping_definition_2.mapped_types = ['Comparison']