Variability Framework: variability_framework_testing Namespace Reference
variability_framework_testing Namespace Reference
Functions
def collect_perspective_against_framework (database_entry_type, grab_classifier, dict direction_flags_dict, graph)
This module provides tools for testing collected differences against a particular variability framework (or set of conditions)
def identify_element_type_from_mapping (node_tag, type_mapping)
def identify_relationship_class_from_mapping (relationship_tag, relationship_mapping, framework_module)
def test_perspective_against_framework (database_entry_type, type_mapping, relationship_mapping, thing_uid_list, thing_list, diff_database_compliance, grab_classifier, framework_module, graph)
def test_database_against_framework (labeled_types, type_mapping, relationship_mapping, thing_uid_list, thing_list, diff_database_compliance, framework_module, graph)
def explore_database_perspective (database_entry_type, thing_uid_list, thing_list, relationship_edges, grab_classifier, graph)
def explore_difference_database (labeled_types, thing_uid_list, thing_list, relationship_edges, controlled_flag, graph)
def association_rule_mining_apriori (relationship_edges)
def convert_apriori_rules (labeled_types, apriori_results)
def identify_type_hierachy (rules)
def write_relationship_class (framework_file, relationship_name)
def write_type_class (framework_file, type_name, parent)
def write_rules_to_framework_file (apriori_rules, filename)
def main ()
Variables
framework_module = variability_definition_1
mapping_module = mapping_definition_1
Function Documentation
association_rule_mining_apriori()
def variability_framework_testing.association_rule_mining_apriori (relationship_edges)
References association_rule_mining_apriori().
Referenced by association_rule_mining_apriori(), and main().
collect_perspective_against_framework()
def variability_framework_testing.collect_perspective_against_framework (database_entry_type, grab_classifier, dict direction_flags_dict, graph)
This module provides tools for testing collected differences against a particular variability framework (or set of conditions)
References collect_perspective_against_framework(), and database_tools.run_neo_query().
Referenced by collect_perspective_against_framework(), explore_database_perspective(), and test_perspective_against_framework().
convert_apriori_rules()
def variability_framework_testing.convert_apriori_rules (labeled_types, apriori_results)
References convert_apriori_rules().
Referenced by convert_apriori_rules(), and main().
explore_database_perspective()
def variability_framework_testing.explore_database_perspective (database_entry_type, thing_uid_list, thing_list, relationship_edges, grab_classifier, graph)
References collect_perspective_against_framework(), and explore_database_perspective().
Referenced by explore_database_perspective(), and explore_difference_database().
explore_difference_database()
def variability_framework_testing.explore_difference_database (labeled_types, thing_uid_list, thing_list, relationship_edges, controlled_flag, graph)
References explore_database_perspective(), and explore_difference_database().
Referenced by explore_difference_database(), and main().
identify_element_type_from_mapping()
def variability_framework_testing.identify_element_type_from_mapping (node_tag, type_mapping)
References identify_element_type_from_mapping().
Referenced by identify_element_type_from_mapping(), and test_perspective_against_framework().
identify_relationship_class_from_mapping()
def variability_framework_testing.identify_relationship_class_from_mapping (relationship_tag, relationship_mapping, framework_module)
References identify_relationship_class_from_mapping().
Referenced by identify_relationship_class_from_mapping(), and test_perspective_against_framework().
identify_type_hierachy()
def variability_framework_testing.identify_type_hierachy (rules)
References identify_type_hierachy().
Referenced by identify_type_hierachy(), and main().
main()
def variability_framework_testing.main ()
References association_rule_mining_apriori(), convert_apriori_rules(), explore_difference_database(), identify_type_hierachy(), main(), variability_framework_core.Rules.parse_rules(), and write_rules_to_framework_file().
Referenced by main().
test_database_against_framework()
def variability_framework_testing.test_database_against_framework (labeled_types, type_mapping, relationship_mapping, thing_uid_list, thing_list, diff_database_compliance, framework_module, graph)
References test_database_against_framework(), and test_perspective_against_framework().
Referenced by test_database_against_framework().
test_perspective_against_framework()
def variability_framework_testing.test_perspective_against_framework (database_entry_type, type_mapping, relationship_mapping, thing_uid_list, thing_list, diff_database_compliance, grab_classifier, framework_module, graph)
References collect_perspective_against_framework(), identify_element_type_from_mapping(), identify_relationship_class_from_mapping(), and test_perspective_against_framework().
Referenced by test_database_against_framework(), and test_perspective_against_framework().
write_relationship_class()
def variability_framework_testing.write_relationship_class (framework_file, relationship_name)
References write_relationship_class().
Referenced by write_relationship_class(), and write_rules_to_framework_file().
write_rules_to_framework_file()
def variability_framework_testing.write_rules_to_framework_file (apriori_rules, filename)
References write_relationship_class(), write_rules_to_framework_file(), and write_type_class().
Referenced by main(), and write_rules_to_framework_file().
write_type_class()
def variability_framework_testing.write_type_class (framework_file, type_name, parent)
References write_type_class().
Referenced by write_rules_to_framework_file(), and write_type_class().
Variable Documentation
framework_module
variability_framework_testing.framework_module = variability_definition_1
mapping_module
variability_framework_testing.mapping_module = mapping_definition_1